import SideBar from "../components/SideBar";
import "./globals.css";

export const metadata = {
    title: "AI Music",
    description: "Generated by AI",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" className="bg-myblack">
            <body className="container mx-auto overflow-hidden">
                <div className="bg-primary flex rounded-[60px]">
                    <SideBar />
                    {children}
                </div>
            </body>
        </html>
    );
}
